### ISSUE TITLE
is there's any build for windows ???? and if now how can i build my own version

### ISSUE THREAD

**Issue by ahmad12331233** [Velaron/tf15-client#12]

**Comment by Velaron** [comment]
just use the game from steam, this if for android

**Comment by ahmad12331233** [comment]
but my friends play on android and i don't have android device

**Comment by ahmad12331233** [comment]
but ok fine :(

**Comment by Velaron** [comment]
They don't, because this is unfinished and hasn't released yet...

**Comment by Velaron** [comment]
And using the Windows version doesn't stop you from playing with friends.

**Comment by Velaron** [comment]
Original TFC works under Xash3D

**Comment by ahmad12331233** [comment]
ok....







wait a minute how my friends play tfc???

**Comment by ahmad12331233** [comment]
ok thanks for information
and i will check if my friends lying to me

**Comment by ahmad12331233** [comment]
bye
