### ISSUE TITLE
Is there is a Server DLL?

### ISSUE THREAD

**Issue by bariscodefxy** [Velaron/tf15-client#32]
Is there is a Server DLL?

**Comment by AruMoon** [comment]
Sadly, no. Use one from Steam version

**Comment by bariscodefxy** [comment]
> Sadly, no. Use one from Steam version

I using but i cant see player models with this client.

**Comment by bariscodefxy** [comment]
This client have bugs, i will try to fix it in my fork.

**Comment by bariscodefxy** [comment]
> This client have bugs, i will try to fix it in my fork.

I found this problem from windows, works on linux.

**Comment by Vladislav4KZ** [comment]
> > This client have bugs, i will try to fix it in my fork.
> 
> I found this problem from windows, works on linux.

Someone from the discord wrote that he had the same problem on android.

I don't have this problem on windows or android.

**Comment by Velaron** [comment]
Make sure you are using the steam build and not the free mod version, they are very different.

**Comment by bariscodefxy** [comment]
> Make sure you are using the steam build and not the free mod version, they are very different.

I was setup a server with xashds and i downloaded files with steamcmd, and i didn't get any errors. So this problem from server.

**Comment by Vladislav4KZ** [comment]
> I was setup a server with xashds and i downloaded files with steamcmd, and i didn't get any errors. So this problem from server.

Device dependent bug. I tested tfc files from steamcmd on Windows and Android. The server has nothing to do with it.
