### ISSUE TITLE
Не работают аргументы командной строки с лаунчера tf15-client

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/tf15-client#34]
Вместо этого, игра запускается с аргументами, указанными в лаунчере Xash3D FWGS.

**Comment by Mockay** [comment]
https://github.com/Velaron/tf15-client/issues/34#issue-1354230630

**Comment by Mockay** [comment]
https://github.com/Velaron/tf15-client/issues/34#issue-1354230630
