### ISSUE TITLE
Не собирается tfc_arm64.so

### ISSUE THREAD

**Issue by ArtemS2** [Velaron/tf15-client#38]
При сборке не хватает библиотеки tfc.

**Comment by nekonomicon** [comment]
Ее и не должно быть.
Проект называется tf15-client, потому что здесь пока только исходники клиента.

**Comment by ArtemS2** [comment]
Понятно, жалко. Я ее вообще никак не собрать?

**Comment by nekonomicon** [comment]
Valve никогда не открывала исходники tfc, не считая каких-то кусков в клиентской части в обычном HLSDK, а серверку пока никто не написал.
То есть пока на альтернативных платформах можно подключаться только к готовым серверам.

**Comment by ArtemS2** [comment]
А как же сейчас люди играют через клиент, если полной совместимости xash и goldsource в сетевой части пока нет?

**Comment by Vladislav4KZ** [comment]
> А как же сейчас люди играют через клиент, если полной совместимости xash и goldsource в сетевой части пока нет?

Так серверы работают на ксаше, с использованием оригинальной серверной библиотеки TFC для Linux или Windows. Только она сделала для архитектуры x86, на arm64 она не будет работать.

**Comment by ArtemS2** [comment]
Понятненько

**Comment by nickbailuc** [comment]
@ArtemS2 
На какой платформе ты используешь cs16, мне просто интересно. У меня проблемы с подключением к любому серверу, но я запускаю его на arm64-linux-gnu (не Android), отсутствует графическая библиотека или что-то в этом роде, хотя другие игры и моды xash компилируются и работают нормально с меню и всем остальным. 

Я могу подключиться к серверу cs16, но не могу открыть team/character select

**Comment by ArtemS2** [comment]
@nickbailuc Привет! Я запускал cs16 на своем Orange PI5B (ОС: Ubuntu Arm64) , вроде все нормально работает на последней версии движка. У меня есть ТГ канал "Orange pi 5. Games" , там выложил, то как у меня это получилось.

**Comment by nekonomicon** [comment]
> amx mod выбора команд и закупок.

Нет.
Я точно не помню, но в TFC могло остаться текстовое меню от старых версий без vgui.

**Comment by ArtemS2** [comment]
@nekonomicon А есть шанс, что в будущем появится серверная часть tfc, как в cs16?

**Comment by nekonomicon** [comment]
В случае с CS 1.6 изначально брали реализацию CSDM от O'Neill за основу клиента, а насчет серверной части - по началу и не предполагалось использовать какую-то готовую реализацию, но таки сначала попробовали CS16ND от @nagist, потом перешли на regamedll_cs так как эта реализация была более точной и стабильной.
А серверку TFC я начинал реверсить, толком не помню почему изначально забросил, но тут еще @Velaron по личным причинам удалял репозиторий, и я из-за работы и хронического воспаления век не уделял толком время своим проектам.

**Comment by Velaron** [comment]
Moved here https://github.com/Velaron/tf15-client/issues/44
