### ISSUE TITLE
Is it possible to play with bots? 

### ISSUE THREAD

**Issue by Passeunebonnejournee** [Velaron/tf15-client#40]
I have tried to install foxbot but it doesn't work, I would like it to work to play offline, because there is usually no one on the public servers, it is a shame, it is a good port
I will support this project by donating monthly if possible

**Comment by Velaron** [comment]
No, as this would require reverse-engineering the server and that's very tough and takes lots of time, I host a server with bots most of the time but somtimes it crashes

**Comment by Passeunebonnejournee** [comment]
How could I then play the server with bots? Mostly when I go in to play there is no one on the servers  

thank you very much for your attention

**Comment by Velaron** [comment]
You can host a setver or any PC/VPS using xash3d-fwgs with regular TFC and Foxbot

**Comment by Yashar1991** [comment]
Help Why I can't create game my self 
Help!!!!!!! And I went to play with bots but how we can join they!?

**Comment by Velaron** [comment]
Moved here https://github.com/Velaron/tf15-client/issues/44
