### ISSUE TITLE
Отсутствует tfc_amd64.so

### ISSUE THREAD

**Issue by ConLenov** [Velaron/tf15-client#41]
В последнем Release отсутствует библиотека tfc_amd64.so Добавьте плиз в бинарник tfc_amd64.so или хотя бы сделайте возможность сборки библиотеки tfc_amd64.so

Моя система: 64-битный Linux и я хочу поставить TFC на Xash3D

**Comment by nekonomicon** [comment]
Дубль https://github.com/Velaron/tf15-client/issues/38 и  https://github.com/Velaron/tf15-client/issues/39

> В последнем Release отсутствует библиотека tfc_amd64.so Добавьте плиз в бинарник tfc_amd64.so или хотя бы сделайте возможность сборки библиотеки tfc_amd64.so

Этого не будут, потому что исходников серверной части нет

> Моя система: 64-битный Linux и я хочу поставить TFC на Xash3D

И кто тебе мешает поставить мультилиб на 64-битный линукс?

**Comment by Velaron** [comment]
Moved here https://github.com/Velaron/tf15-client/issues/44
