### ISSUE TITLE
The animation of a sniper rifle shot is not displayed.

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/tf15-client#6]
TFC on PC version Xash3D FWGS helps cl_lw 0 cvar (Original Steam version client.dll and tfc.dll)

On android animation does not play at all

Compiled latest TFC launcher for Android with b03aa6f commit

**Comment by Velaron** [comment]
releases are auto-updated (even if the date doesn't change)
and sniper rifle isn't finished for now because of bad decompiler output

**Comment by Velaron** [comment]
working for me, are you sure it's not just because it doesn't fire when you are moving?

**Comment by Velaron** [comment]
sorry, i forgot i was testing under goldsrc, it's an engine prediction bug and i have no idea how to fix it

**Comment by Vladislav4KZ** [comment]
Не знаю почему тогда анимация не работала, сейчас выключил cl_lw и анимация появилась.

Тогда даже cl_lw 0 не помогал

**Comment by Velaron** [comment]
с оригинальным клиентом cl_lw вроде вырубить нельзя, как минимум у меня тогда движок вылетает, а с моим да, должно "починить"

**Comment by Velaron** [comment]
пофикшено в движке

**Comment by Vladislav4KZ** [comment]
Да, пофикшено на андроиде но на Windows до сих пор остался баг
Движок, я естественно обновил

**Comment by Vladislav4KZ** [comment]
Даже так, баг остался только на ЛОКАЛЬНОМ сервере, при подключении к другим серверам анимация работает с cl_lw 1
