### ISSUE TITLE
After changing the level on server, the game writes about the missing sprite crosszoom.spr

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/tf15-client#7]
Restarting the game completely resolves this issue. This sprite is not in the game files, and should not be.

**Comment by Velaron** [comment]
the server doesn't use client library, so it's valve problem

**Comment by Velaron** [comment]
can i have a screenshot of this or something?

**Comment by Vladislav4KZ** [comment]
![Screenshot_20210305-182706.png](https://user-images.githubusercontent.com/22411953/110115607-85733b80-7de0-11eb-963c-188f9bbcba36.png)

**Comment by Velaron** [comment]
what's inside tf_weapon_superng.txt? just wondering

**Comment by Vladislav4KZ** [comment]
It looks like there were broken files. Reinstalled tfc files now this bug is gone.
