### ISSUE TITLE
баг с отображением команды

### ISSUE THREAD

**Issue by Skyrim-police** [Velaron/tf15-client#8]
игра показывает что противник в спектаторе хотя на самом деле это не так 
![Screenshot_2021-02-28-21-21-21-221_su.xash.engine.jpg](https://user-images.githubusercontent.com/65493638/109695000-143f4880-7b94-11eb-9cb4-348c28ac1142.jpg)

**Comment by Velaron** [comment]
возможно связано с кривыми конфигами

**Comment by Velaron** [comment]
больше не воспроизводилось
